if flame_dungeon . is_flamed ( d . get_map_index ( ) ) and d . getf ( "level" ) == 17 then notice_multiline ( "Razador " .. pc . get_name ( ) .. " grubu tarafýndan yok edildi." , d . notice ) 
notice_multiline ( "Ejderha Tapýnaðý içindeki Tüm Savaþcýlar [ENTER]Bir dakika içerisinde ýþýnlanacaktýr." , d . notice ) 
timer ( "exit_dungeon" , 60 ) 
flame_dungeon . level_clear ( ) 
if party . is_party ( ) then 
party . setf ( "flame_dungeon_boss_kill_count" , 1 ) 
end 
 return end 